/**
 * appEvents — product telemetry for the Owner Console (public.app_events,
 * public.app_installs; supabase/v1_6_owner_console.sql).
 *
 * TWO SOURCES, LABELLED SEPARATELY
 *   server  Recorded here from the outcome of an API request that already
 *           happened (route template + status code). Trusted: the user id is
 *           the verified token's, and nothing is recorded unless the request
 *           reached a known route. Route handlers are not modified.
 *   client  Reported by the app to POST /api/telemetry/events: first launch,
 *           app open, sign-in outcomes (which happen directly against
 *           Supabase Auth, so the server never sees them) and crashes. The
 *           endpoint accepts anonymous first launches, so these are
 *           self-reported counts.
 *
 * PRIVACY
 *   Event names and property keys are allow-listed; property values are enums,
 *   short codes or small integers. No amounts, descriptions, merchants,
 *   statement text, AI questions or answers, emails, tokens, IPs or device
 *   identifiers are stored. An install id is a random UUID generated by the app.
 *
 * Every write is fire-and-forget and never affects the user's request,
 * including when the v1.6 migration has not been applied.
 */

const { z } = require('zod');

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const PLATFORMS = ['android', 'ios', 'web'];

// ─── Allow-lists ────────────────────────────────────────────────────────────

/** Events the app may report. Anything else is dropped. */
const CLIENT_EVENTS = [
    'first_launch',
    'app_open',
    'signup',
    'signup_failed',
    'login',
    'login_failed',
    'logout',
    'google_sign_in_started',
    'auth_callback_failed',
    'password_reset_requested',
    'password_reset_failed',
    'password_updated',
    'ai_mentor_opened',
    'app_crash',
    // v1.1 monetization (no amounts, merchants or descriptions)
    'subscription_audit_opened',
    'debit_reminder_scheduled',
    'debit_reminder_opened',
    'pro_paywall_viewed',
    'plan_selected',
    'purchase_started',
    'challenge_viewed',
];

/** Events the backend records itself. */
const SERVER_EVENTS = [
    'expense_created', 'expense_create_failed', 'expense_edited', 'expense_deleted',
    'receipt_scanned', 'receipt_scan_failed',
    'csv_exported', 'csv_export_failed',
    'pdf_imported', 'pdf_import_failed',
    'ai_question_answered', 'ai_question_failed',
    'group_created', 'group_joined', 'group_join_failed', 'group_expense_added', 'group_settlement', 'group_left',
    'profile_updated', 'recurring_bill_added', 'subscription_marked_cancelled',
    'account_deleted', 'account_delete_failed',
    'pro_purchase_attempted',
    // v1.1 monetization
    'recurring_payment_confirmed', 'recurring_payment_dismissed', 'price_change_detected', 'recurring_payment_detected',
    'purchase_completed', 'purchase_restored', 'purchase_failed',
    'challenge_joined', 'challenge_completed', 'reward_issued', 'reward_redeemed',
    'student_verification_started', 'student_verification_passed',
];

const code = z.string().regex(/^[a-z0-9_]{1,40}$/);
const PROP_VALIDATORS = {
    method: z.enum(['email', 'google']),
    code,
    kind: z.string().regex(/^[A-Za-z]{1,40}$/),
    status: z.number().int().min(0).max(599),
    source: z.enum(['manual', 'upi_auto', 'ai_scan', 'pdf_import']),
    outcome: z.enum(['ai', 'fallback', 'calculated']),
    intent: z.string().regex(/^[a-z_]{1,30}$/),
    field: z.enum(['budget', 'savings_target']),
    plan: z.enum(['monthly', 'yearly', 'student_monthly', 'student_yearly', 'limited_yearly']),
    decision: z.enum(['confirmed', 'dismissed', 'intentional', 'unwanted', 'cleared']),
    confidence: z.enum(['high', 'medium', 'possible']),
    challenge: z.string().regex(/^[a-z_]{1,40}$/),
};

/** Keep only allow-listed keys whose values pass their validator. */
function sanitizeProps(props) {
    const clean = {};
    if (!props || typeof props !== 'object' || Array.isArray(props)) return clean;
    for (const [key, validator] of Object.entries(PROP_VALIDATORS)) {
        if (props[key] === undefined) continue;
        const parsed = validator.safeParse(props[key]);
        if (parsed.success) clean[key] = parsed.data;
    }
    return clean;
}

// ─── Persistence ────────────────────────────────────────────────────────────

let persistErrorLogged = false;

function client() {
    return require('../config/supabase').supabase;
}

function logPersistError(error) {
    if (error && !persistErrorLogged) {
        persistErrorLogged = true;
        console.error('app_events unavailable (run supabase/v1_6_owner_console.sql):', error.message);
    }
}

/** Insert rows into app_events. Best effort, never throws. */
function insertEvents(rows) {
    if (!rows.length) return Promise.resolve(false);
    let supabase;
    try {
        supabase = client();
    } catch {
        return Promise.resolve(false);
    }
    return Promise.resolve()
        .then(() => supabase.from('app_events').insert(rows))
        .then((result) => {
            logPersistError(result?.error);
            return !result?.error;
        })
        .catch(() => false);
}

/** Record one server-side event. */
function recordServerEvent(name, { userId = null, props, statusCode = null, durationMs = null } = {}) {
    if (!SERVER_EVENTS.includes(name)) return Promise.resolve(false);
    return insertEvents([{
        name,
        source: 'server',
        user_id: userId && UUID_RE.test(userId) ? userId : null,
        props: sanitizeProps(props),
        status_code: statusCode,
        duration_ms: durationMs === null ? null : Math.round(durationMs),
    }]);
}

// ─── Server events from request outcomes ───────────────────────────────────
//
// Keyed by "METHOD /route/template". `ok` is recorded for 2xx, `fail` for
// other statuses except 401 (unauthenticated probes are not product usage).
const outcome = (res) => {
    const o = res.locals?.aiOutcome;
    if (!o) return {};
    return { outcome: o.source === 'ai' ? 'ai' : o.aiFallback ? 'fallback' : 'calculated', intent: o.intent };
};

const ROUTE_EVENTS = {
    'POST /api/expenses': { ok: 'expense_created', fail: 'expense_create_failed', props: (req) => ({ source: req.body?.source === 'upi_auto' ? 'upi_auto' : 'manual' }) },
    'PATCH /api/expenses/:id': { ok: 'expense_edited' },
    'DELETE /api/expenses/:id': { ok: 'expense_deleted' },
    'POST /api/expenses/scan': { ok: 'receipt_scanned', fail: 'receipt_scan_failed' },
    'GET /api/expenses/export.csv': { ok: 'csv_exported', fail: 'csv_export_failed' },
    'POST /api/pdf-import': { ok: 'pdf_imported', fail: 'pdf_import_failed' },
    'POST /api/ai/invest-advice': { ok: 'ai_question_answered', fail: 'ai_question_failed', props: (req, res) => outcome(res) },
    'POST /api/groups': { ok: 'group_created' },
    'POST /api/groups/join': { ok: 'group_joined', fail: 'group_join_failed' },
    'POST /api/groups/:id/expenses': { ok: 'group_expense_added' },
    'POST /api/groups/:id/settle': { ok: 'group_settlement' },
    'DELETE /api/groups/:id/members/me': { ok: 'group_left' },
    'PUT /api/account/budget': { ok: 'profile_updated', props: () => ({ field: 'budget' }) },
    'PUT /api/account/investment-target': { ok: 'profile_updated', props: () => ({ field: 'savings_target' }) },
    'POST /api/safe-to-spend/bills': { ok: 'recurring_bill_added' },
    'POST /api/subscriptions/cancelled': { ok: 'subscription_marked_cancelled' },
    'POST /api/subscription-audit/decision': { ok: 'recurring_payment_confirmed', props: (req) => ({ decision: ['confirmed', 'dismissed', 'intentional', 'unwanted'].includes(req.body?.decision) ? req.body.decision : 'cleared' }) },
    'POST /api/pro/verify-purchase': { ok: 'purchase_completed', fail: 'purchase_failed' },
    'POST /api/challenges/:id/join': { ok: 'challenge_joined' },
    // Account deletion is counted without the (now deleted) user's id.
    'DELETE /api/account': { ok: 'account_deleted', fail: 'account_delete_failed', anonymous: true },
    // Purchases are not implemented (501); an attempt is still a demand signal.
    'POST /api/pro/activate': { ok: 'pro_purchase_attempted', fail: 'pro_purchase_attempted' },
};

/** "METHOD /api/x/:id" for a finished request, without a trailing slash; null if unmatched. */
function routeKey(req) {
    if (!req.route || typeof req.route.path !== 'string') return null;
    const path = `${req.baseUrl || ''}${req.route.path}`.replace(/\/+$/, '') || '/';
    return `${req.method} ${path}`;
}

/** Called when a request finishes (see opsTelemetry.requestMetrics). */
function recordRequestOutcome(req, res, durationMs) {
    const key = routeKey(req);
    const rule = key && ROUTE_EVENTS[key];
    if (!rule) return;
    const status = res.statusCode;
    if (status === 401) return;
    const name = status < 400 ? rule.ok : rule.fail;
    if (!name) return;
    let props = {};
    try {
        props = rule.props ? rule.props(req, res) : {};
    } catch {
        props = {};
    }
    recordServerEvent(name, {
        userId: rule.anonymous ? null : req.user?.id || null,
        props: { ...props, ...(status >= 400 ? { status } : {}) },
        statusCode: status,
        durationMs,
    });
}

// ─── Client batches ─────────────────────────────────────────────────────────

const MAX_BATCH = 25;
const MAX_CLIENT_SKEW_MS = 48 * 60 * 60 * 1000;

const batchSchema = z.object({
    installId: z.string().regex(UUID_RE, 'installId must be a UUID'),
    platform: z.enum(PLATFORMS),
    appVersion: z.string().regex(/^[0-9A-Za-z._+-]{1,32}$/).optional(),
    events: z.array(z.object({
        name: z.string().max(60),
        at: z.string().datetime({ offset: true }).optional(),
        props: z.record(z.string(), z.unknown()).optional(),
    }).strict()).min(1).max(MAX_BATCH),
}).strict();

/** A client timestamp within the last 48h (queued offline), otherwise now. */
function eventTime(at, now) {
    if (!at) return new Date(now).toISOString();
    const t = new Date(at).getTime();
    if (Number.isNaN(t) || t > now + 5 * 60 * 1000 || t < now - MAX_CLIENT_SKEW_MS) return new Date(now).toISOString();
    return new Date(t).toISOString();
}

/**
 * Store a validated client batch: upsert the install, then insert events.
 * @returns {Promise<{accepted: number, stored: boolean}>}
 */
async function ingestClientBatch(batch, { userId = null, now = Date.now() } = {}) {
    const supabase = client();
    const events = batch.events.filter((e) => CLIENT_EVENTS.includes(e.name));

    const { data: existing, error: readError } = await supabase
        .from('app_installs')
        .select('install_id, user_id')
        .eq('install_id', batch.installId)
        .maybeSingle();
    if (readError) {
        logPersistError(readError);
        return { accepted: 0, stored: false };
    }

    const install = {
        install_id: batch.installId,
        platform: batch.platform,
        app_version: batch.appVersion || null,
        last_seen_at: new Date(now).toISOString(),
        // Link to the signed-in account; never unlink from an anonymous batch.
        ...(userId ? { user_id: userId } : {}),
    };
    const { error: upsertError } = await supabase.from('app_installs').upsert(install, { onConflict: 'install_id' });
    if (upsertError) {
        logPersistError(upsertError);
        return { accepted: 0, stored: false };
    }

    // A first launch is counted once per install, however often it is replayed.
    let seenFirstLaunch = Boolean(existing);
    const rows = [];
    for (const e of events) {
        if (e.name === 'first_launch') {
            if (seenFirstLaunch) continue;
            seenFirstLaunch = true;
        }
        rows.push({
            name: e.name,
            source: 'client',
            install_id: batch.installId,
            user_id: userId,
            platform: batch.platform,
            app_version: batch.appVersion || null,
            props: sanitizeProps(e.props),
            created_at: eventTime(e.at, now),
        });
    }
    const stored = rows.length ? await insertEvents(rows) : true;
    return { accepted: stored ? rows.length : 0, stored };
}

module.exports = {
    CLIENT_EVENTS,
    SERVER_EVENTS,
    ROUTE_EVENTS,
    PLATFORMS,
    batchSchema,
    sanitizeProps,
    recordServerEvent,
    recordRequestOutcome,
    ingestClientBatch,
    routeKey,
};
